-- MySQL Script generated by MySQL Workbench
-- Tue Sep 16 15:07:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escola_Tecnica
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Escola_Tecnica` DEFAULT CHARACTER SET utf8 ;
USE `Escola_Tecnica` ;

-- -----------------------------------------------------
-- Table `Escola_Tecnica`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Tecnica`.`Aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Tecnica`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Tecnica`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `carga_horaria` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola_Tecnica`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola_Tecnica`.`Matricula` (
  `id` INT NOT NULL,
  `data_matricula` DATE NULL,
  `aluno` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Matricula_Aluno`
    FOREIGN KEY (`aluno`)
    REFERENCES `Escola_Tecnica`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `Escola_Tecnica`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `aluno` VALUES (1,'João de Souza','joao@gmail.com','2000-02-09'),(2,'Joana de Souza','joana@gmail.com','2000-02-09'),(3,'José de Souza','jose@gmail.com','2000-02-09'),(4,'Maria de Souza','maria@gmail.com','2000-02-09'),(5,'Pedro de Souza','pedro@gmail.com','2000-02-09');

INSERT INTO `curso` VALUES (1,'Matemática Computacional',40),(2,'Banco de Dados',80),(3,'Programação Orientada a Objetos',120);

INSERT INTO `matricula` VALUES (1,'2025-09-09',5,1),(2,'2023-10-01',4,2),(3,'2020-10-01',2,3),(4,'2021-10-01',1,3);

