-- MySQL Script generated by MySQL Workbench
-- Tue Oct 14 16:03:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_online` DEFAULT CHARACTER SET utf8 ;
USE `loja_online` ;

-- -----------------------------------------------------
-- Table `loja_online`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_online`.`Produto` (
  `idPro` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT(100) NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tipo` ENUM('novo', 'usado', 'liquidação', 'promoção', 'outros') NULL,
  `categoria` SET('Eletronico', 'Telefonia', 'Informatica', 'Eletrodomesticos', 'Acessorios', 'Outros') NULL DEFAULT 'eletronico',
  `data` DATE NULL,
  `desconto_usado` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idPro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_online`.`Características`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_online`.`Características` (
  `idCarac` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` TEXT(100) NULL,
  PRIMARY KEY (`idCarac`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `loja_online`.`Produto_Características`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_online`.`Produto_Características` (
  `produto` INT NOT NULL,
  `caracteristica` INT NOT NULL,
  `id_pro_carac` INT NOT NULL,
  INDEX `fk_Produto_Características_Produto2_idx` (`produto` ASC) ,
  INDEX `fk_Produto_Características_Características2_idx` (`caracteristica` ASC) ,
  PRIMARY KEY (`id_pro_carac`),
  CONSTRAINT `fk_Produto_Características_Produto2`
    FOREIGN KEY (`produto`)
    REFERENCES `loja_online`.`Produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Características_Características2`
    FOREIGN KEY (`caracteristica`)
    REFERENCES `loja_online`.`Características` (`idCarac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_online`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_online`.`Loja` (
  `idLoja` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(200) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_online`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_online`.`Estoque` (
  `quantidade` INT NOT NULL,
  `loja` INT NOT NULL,
  `Produto` INT NOT NULL,
  `idEstoque` INT NULL,
  INDEX `fk_Estoque_Loja1_idx` (`loja` ASC) ,
  INDEX `fk_Estoque_Produto1_idx` (`Produto` ASC) ,
  PRIMARY KEY (`idEstoque`),
  CONSTRAINT `fk_Estoque_Loja1`
    FOREIGN KEY (`loja`)
    REFERENCES `loja_online`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto`)
    REFERENCES `loja_online`.`Produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert INTO Caracteristicas values (1, 'Bateria', 'Duração da bateria em horas');
insert INTO Caracteristicas values (2, 'Tela', 'Tamanho e resolução da tela');
insert INTO Caracteristicas values (3, 'Processador', 'Modelo e velocidade do processador');
insert INTO Caracteristicas values (4, 'Memória RAM', 'Capacidade da memória RAM em GB');
insert INTO Caracteristicas values (5, 'Armazenamento', 'Capacidade de armazenamento interno');
insert INTO Caracteristicas values (6, 'Conectividade', 'Tipos de conexão suportados (Wi-Fi, Bluetooth)');
insert INTO Caracteristicas values (7, 'Peso', 'Peso do produto em gramas');
insert INTO Caracteristicas values (8, 'Câmera', 'Resolução e características da câmera');
insert INTO Caracteristicas values (9, 'Sistema Operacional', 'Sistema operacional instalado');
insert INTO Caracteristicas values (10, 'Cor', 'Cor do produto');
insert INTO Caracteristicas values (11, 'Garantia', 'Tempo de garantia do produto');
insert INTO Caracteristicas values (12, 'Dimensões', 'Medidas físicas do produto');
insert INTO Caracteristicas values (13, 'Voltagem', 'Voltagem compatível do aparelho');
insert INTO Caracteristicas values (14, 'Material', 'Material predominante na fabricação');
insert INTO Caracteristicas values (15, 'Compatibilidade', 'Compatível com quais dispositivos ou sistemas');
